# Generated by Django 2.0 on 2020-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200809_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='readed_num',
        ),
        migrations.AddField(
            model_name='blog',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
